Few minor fixes
- lsof on ubuntu complains about tracefs to stderr => filtered
- handling more ports on ssh process

diff --git a/socks-via-ssh/sstun b/socks-via-ssh/sstun
--- a/socks-via-ssh/sstun
+++ b/socks-via-ssh/sstun
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # Author: Martin 'BruXy' Bruchanov, bruchy at gmail
-# Version: 1.1 (Sun Nov 10 23:37:54 AST 2019)
+# Version: 1.2 (Thu Nov 14 13:53:02 AST 2019)
 #
 # URL: http://bruxy.regnet.cz/web/linux/EN/socks-via-ssh/
 # GitHub: https://github.com/BruXy/bash-utils/tree/master/socks-via-ssh
@@ -78,9 +78,16 @@ function print_help() {
 
 function get_child_pid() {
     local pid=$1
+    # check if $pid of parent exists
+    if ! kill -0 "$pid" >& /dev/null ; then
+        printf "$0 ERROR -- Process PID %d does not exists!\n" "$pid"
+        return
+    fi 
+    # get child PID
     local retval=$(ps --ppid $pid -h -o pid)
     if [ -z "$retval" ] ; then
         printf "$0 WARNING -- Cannot find child process of %d!\n" $pid
+    return
     else
         echo $retval
     fi
@@ -229,15 +236,22 @@ function ip_status() {
             child_pid=$(get_child_pid $ppid)
             printf "$0: INFO -- %s autossh (ppid: %d) -> ssh (pid: %d)\n" \
                 "$host" "$ppid" "$child_pid"
-            port=$(lsof -P -p $child_pid | \
+            # Note 1: lsof on Ubuntu complains about tracefs to stderr,
+            #         filtered by '|&'
+            # Note 2: I have some connections with more then one tunnel.
+            ports=$(lsof -P -p $child_pid |& \
                     sed -ne 's/.* localhost:\([0-9]*\) .*/\1/p' | uniq)
-            remote_ip=$(curl --silent --socks5 $TUN_BIND:$port http://ifconfig.co/)
-            if [ ! -z "$remote_ip" ] ; then
-                echo "$0: SOCKS proxy $TUN_BIND:$port connects via: $remote_ip, "\
-                    $(dig +short -x $remote_ip | sed -e "s/\.%//")
-            else
-                printf "$0: No proxy enabled on port '%d', (pid=%d)!\n" "$port" "$pid"
-            fi
+            for p in $ports
+            do
+                remote_ip=$(curl --silent --socks5 $TUN_BIND:$p \
+                    http://ifconfig.co/)
+                if [ ! -z "$remote_ip" ] ; then
+                    echo "$0: SOCKS proxy $host ($TUN_BIND:$p) connects via: $remote_ip, "\
+                        $(dig +short -x $remote_ip | sed -e "s/\.%//")
+                else
+                    printf "$0: $host has no proxy enabled on port '%d', (pid=%d)!\n" "$p" "$pid"
+                fi
+            done
         done
     else
         printf "$0: ERROR -- No lock file found, was sstun started?\n" >&2
